#!/usr/bin/env python3
"""Generate synthetic DOCX fixtures of controlled size for the load harness.

Real-toolchain provenance, matching `scripts/generate-upload-corpus.py`: every
fixture is produced by python-docx, so it is genuine Word-compatible OOXML and
travels the same upload, package-limits and extraction path as a real document.
Content is deterministic, fictional legal correspondence — no client matter
data and nothing identifying this run.

Size control is paragraph count times words per paragraph, and the text is
generated by a seeded PRNG over a wide vocabulary. That is deliberate: a
repeating pattern compresses to almost nothing in the ZIP, so a "large" fixture
built from a short repeating block arrives on the wire as a small one and the
test measures nothing. The resulting byte size is reported by the generator and
re-checked by the harness, because no script can promise a deflated size in
advance.

Usage:
  python3 scripts/load/make-upload-fixtures.py --out <dir> --sizes small,medium,large
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

# (paragraphs, words per paragraph). Calibrated against measured output rather
# than derived from a ratio: the numbers are what produced roughly 40 KB,
# 400 KB and 2 MB, comfortably inside the API's 25 MiB multipart cap.
SHAPES = {
    "small": (40, 90),
    "medium": (1_600, 110),
    "large": (6_000, 150),
}

VOCABULARY = (
    "boundary fence title plan covenant easement conveyance leasehold counterpart "
    "schedule undertaking indemnity warranty notice disclosure inspection survey "
    "valuation dilapidations forfeiture assignment subletting consent premium arrears "
    "service charge management surveyor instructed observed inspected correspondence "
    "without prejudice privilege enclosure annexure executed attested witnessed "
    "solicitor counsel opinion advice instruction retainer undertaking disclosure "
    "Cartwright Penhallow Aldridge Whitcombe Fairweather Millbrook Ashcombe "
    "March September November January February June July October December "
    "freehold registered unregistered possessory adverse occupation encroachment "
    "restrictive positive obligation transferor transferee lessor lessee "
    "determination re-entry forfeit remedy injunction specific performance "
    "nuisance trespass negligence misrepresentation estoppel rectification "
    "trust beneficiary executor administrator probate intestacy residue "
    "consideration apportionment reconciliation reconciliation retention "
    "disbursement statement reconciliation interest penalty termination "
    "renewal option break clause review rent deposit guarantee surety "
    "development plot dwelling unit phase planning permission condition "
    "highway drainage easement covenant restriction transfer deed "
    "executed counterpart original engrossment certified copy bundle "
    "exhibit appendix chronology statement case authorities skeleton argument "
    "submissions hearing directions order judgment reasons conclusion "
    "professional negligence limitation contribution indemnity insurance "
    "quantum assessment evidence witness statement attendance note "
    "enquiry requisition reply requisitions completion completion date "
    "exchange deposit contract conditions standard conditions special conditions "
    "settlement compromise without admission confidentiality undertaking "
    "consent order tomlin schedule agreement compromise"
).split()

REFERENCES = (
    "AB{c:06d}",
    "[{y}] EWHC {n} (Ch)",
    "[{y}] EWCA Civ {n}",
    "T{r:07d}",
    "Ref {c:06d}/{y}",
    "Exhibit {m}{n}",
)


def _prng(seed: int):
    """xorshift32: deterministic, long period, no dependency on `random`."""

    state = seed & 0xFFFFFFFF or 0x9E3779B9

    def next_int(bound: int) -> int:
        nonlocal state
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= state >> 17
        state ^= (state << 5) & 0xFFFFFFFF
        return state % bound

    return next_int


def paragraph_text(next_int, words: int) -> str:
    tokens = []
    for position in range(words):
        token = VOCABULARY[next_int(len(VOCABULARY))]
        if position == 0:
            token = token.capitalize()
        # Legal prose carries references; they also defeat dictionary-only
        # compression, which is what makes the larger fixtures actually larger.
        if position % 12 == 7:
            template = REFERENCES[next_int(len(REFERENCES))]
            token = f"{token} {template.format(c=next_int(999999), y=1998 + next_int(29), n=next_int(1999), r=next_int(9999999), m='A' * (1 + next_int(2)))}"
        tokens.append(token)
    return " ".join(tokens) + "."


def build(paragraphs: int, words: int):
    from docx import Document

    document = Document()
    document.add_heading("Synthetic load fixture", level=1)
    next_int = _prng(paragraphs * 2654435761 + words)
    for index in range(paragraphs):
        document.add_paragraph(f"{index + 1}. {paragraph_text(next_int, words)}")

    # python-docx stamps dc:description with "generated by python-docx", which
    # the extraction-coverage guard rightly refuses as unexamined docProps text
    # (see scripts/generate-upload-corpus.py). Its property setter ignores empty
    # values, so drop the element rather than assigning to it.
    core = document.core_properties._element  # noqa: SLF001 (script surgery)
    description = core.find("{http://purl.org/dc/elements/1.1/}description")
    if description is not None:
        core.remove(description)
    document.core_properties.author = ""
    document.core_properties.last_modified_by = ""
    return document


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="directory to write into")
    parser.add_argument(
        "--sizes",
        default=",".join(SHAPES),
        help="comma-separated subset of " + ",".join(SHAPES),
    )
    args = parser.parse_args()

    sizes = [name.strip() for name in args.sizes.split(",") if name.strip()]
    unknown = [name for name in sizes if name not in SHAPES]
    if unknown:
        parser.error(f"unknown size(s): {', '.join(unknown)}")

    os.makedirs(args.out, exist_ok=True)
    manifest = []
    for name in sizes:
        paragraphs, words = SHAPES[name]
        path = os.path.join(args.out, f"load-fixture-{name}.docx")
        build(paragraphs, words).save(path)
        with open(path, "rb") as handle:
            payload = handle.read()
        manifest.append(
            {
                "size": name,
                "path": path,
                "bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest(),
                "paragraphs": paragraphs,
                "words": paragraphs * words,
            }
        )

    json.dump(manifest, sys.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
