/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MattersIndexRouteImport } from './routes/matters/index'
import { Route as MattersMatterIdRouteImport } from './routes/matters/$matterId'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'
import { Route as CaseCaseSlugRouteImport } from './routes/case/$caseSlug'
import { Route as MattersMatterIdDocumentsDocumentIdRouteImport } from './routes/matters/$matterId/documents/$documentId'
import { Route as MattersMatterIdDocumentsDocumentIdRedactRunIdRouteImport } from './routes/matters/$matterId/documents/$documentId/redact/$runId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIndexRoute = MattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersMatterIdRoute = MattersMatterIdRouteImport.update({
  id: '/matters/$matterId',
  path: '/matters/$matterId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseSlugRoute = CaseCaseSlugRouteImport.update({
  id: '/case/$caseSlug',
  path: '/case/$caseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersMatterIdDocumentsDocumentIdRoute =
  MattersMatterIdDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => MattersMatterIdRoute,
  } as any)
const MattersMatterIdDocumentsDocumentIdRedactRunIdRoute =
  MattersMatterIdDocumentsDocumentIdRedactRunIdRouteImport.update({
    id: '/redact/$runId',
    path: '/redact/$runId',
    getParentRoute: () => MattersMatterIdDocumentsDocumentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/case/$caseSlug': typeof CaseCaseSlugRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/matters/$matterId': typeof MattersMatterIdRouteWithChildren
  '/matters/': typeof MattersIndexRoute
  '/matters/$matterId/documents/$documentId': typeof MattersMatterIdDocumentsDocumentIdRouteWithChildren
  '/matters/$matterId/documents/$documentId/redact/$runId': typeof MattersMatterIdDocumentsDocumentIdRedactRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/case/$caseSlug': typeof CaseCaseSlugRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/matters/$matterId': typeof MattersMatterIdRouteWithChildren
  '/matters': typeof MattersIndexRoute
  '/matters/$matterId/documents/$documentId': typeof MattersMatterIdDocumentsDocumentIdRouteWithChildren
  '/matters/$matterId/documents/$documentId/redact/$runId': typeof MattersMatterIdDocumentsDocumentIdRedactRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/case/$caseSlug': typeof CaseCaseSlugRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/matters/$matterId': typeof MattersMatterIdRouteWithChildren
  '/matters/': typeof MattersIndexRoute
  '/matters/$matterId/documents/$documentId': typeof MattersMatterIdDocumentsDocumentIdRouteWithChildren
  '/matters/$matterId/documents/$documentId/redact/$runId': typeof MattersMatterIdDocumentsDocumentIdRedactRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/sign-in'
    | '/workspace'
    | '/case/$caseSlug'
    | '/cases/$caseId'
    | '/matters/$matterId'
    | '/matters/'
    | '/matters/$matterId/documents/$documentId'
    | '/matters/$matterId/documents/$documentId/redact/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/sign-in'
    | '/workspace'
    | '/case/$caseSlug'
    | '/cases/$caseId'
    | '/matters/$matterId'
    | '/matters'
    | '/matters/$matterId/documents/$documentId'
    | '/matters/$matterId/documents/$documentId/redact/$runId'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/sign-in'
    | '/workspace'
    | '/case/$caseSlug'
    | '/cases/$caseId'
    | '/matters/$matterId'
    | '/matters/'
    | '/matters/$matterId/documents/$documentId'
    | '/matters/$matterId/documents/$documentId/redact/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  WorkspaceRoute: typeof WorkspaceRoute
  CaseCaseSlugRoute: typeof CaseCaseSlugRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  MattersMatterIdRoute: typeof MattersMatterIdRouteWithChildren
  MattersIndexRoute: typeof MattersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/': {
      id: '/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof MattersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$matterId': {
      id: '/matters/$matterId'
      path: '/matters/$matterId'
      fullPath: '/matters/$matterId'
      preLoaderRoute: typeof MattersMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseSlug': {
      id: '/case/$caseSlug'
      path: '/case/$caseSlug'
      fullPath: '/case/$caseSlug'
      preLoaderRoute: typeof CaseCaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$matterId/documents/$documentId': {
      id: '/matters/$matterId/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/matters/$matterId/documents/$documentId'
      preLoaderRoute: typeof MattersMatterIdDocumentsDocumentIdRouteImport
      parentRoute: typeof MattersMatterIdRoute
    }
    '/matters/$matterId/documents/$documentId/redact/$runId': {
      id: '/matters/$matterId/documents/$documentId/redact/$runId'
      path: '/redact/$runId'
      fullPath: '/matters/$matterId/documents/$documentId/redact/$runId'
      preLoaderRoute: typeof MattersMatterIdDocumentsDocumentIdRedactRunIdRouteImport
      parentRoute: typeof MattersMatterIdDocumentsDocumentIdRoute
    }
  }
}

interface MattersMatterIdDocumentsDocumentIdRouteChildren {
  MattersMatterIdDocumentsDocumentIdRedactRunIdRoute: typeof MattersMatterIdDocumentsDocumentIdRedactRunIdRoute
}

const MattersMatterIdDocumentsDocumentIdRouteChildren: MattersMatterIdDocumentsDocumentIdRouteChildren =
  {
    MattersMatterIdDocumentsDocumentIdRedactRunIdRoute:
      MattersMatterIdDocumentsDocumentIdRedactRunIdRoute,
  }

const MattersMatterIdDocumentsDocumentIdRouteWithChildren =
  MattersMatterIdDocumentsDocumentIdRoute._addFileChildren(
    MattersMatterIdDocumentsDocumentIdRouteChildren,
  )

interface MattersMatterIdRouteChildren {
  MattersMatterIdDocumentsDocumentIdRoute: typeof MattersMatterIdDocumentsDocumentIdRouteWithChildren
}

const MattersMatterIdRouteChildren: MattersMatterIdRouteChildren = {
  MattersMatterIdDocumentsDocumentIdRoute:
    MattersMatterIdDocumentsDocumentIdRouteWithChildren,
}

const MattersMatterIdRouteWithChildren = MattersMatterIdRoute._addFileChildren(
  MattersMatterIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  WorkspaceRoute: WorkspaceRoute,
  CaseCaseSlugRoute: CaseCaseSlugRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  MattersMatterIdRoute: MattersMatterIdRouteWithChildren,
  MattersIndexRoute: MattersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
