/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MattersIndexRouteImport } from './routes/matters/index'
import { Route as MattersMatterIdRouteImport } from './routes/matters/$matterId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIndexRoute = MattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersMatterIdRoute = MattersMatterIdRouteImport.update({
  id: '/matters/$matterId',
  path: '/matters/$matterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/matters/': typeof MattersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/matters': typeof MattersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/matters/': typeof MattersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/workspace'
    | '/matters/$matterId'
    | '/matters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/workspace' | '/matters/$matterId' | '/matters'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/workspace'
    | '/matters/$matterId'
    | '/matters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  WorkspaceRoute: typeof WorkspaceRoute
  MattersMatterIdRoute: typeof MattersMatterIdRoute
  MattersIndexRoute: typeof MattersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/': {
      id: '/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof MattersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$matterId': {
      id: '/matters/$matterId'
      path: '/matters/$matterId'
      fullPath: '/matters/$matterId'
      preLoaderRoute: typeof MattersMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  WorkspaceRoute: WorkspaceRoute,
  MattersMatterIdRoute: MattersMatterIdRoute,
  MattersIndexRoute: MattersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
