import {
  DRAWINGML_MAIN_NAMESPACE,
  DRAWINGML_PICTURE_NAMESPACE,
  MATH_NAMESPACE,
  WP14_NAMESPACE,
  WPC_NAMESPACE,
  WP_DRAWING_NAMESPACE,
  WPG_NAMESPACE,
  WPS_NAMESPACE,
} from './share-safe-parts'

/**
 * The bounded embedded vocabulary: DrawingML, picture, wordprocessing-
 * drawing, OMML and the Word extension shape namespaces a kept part may
 * emit, plus the unqualified attribute names embedded elements may carry.
 * An element whose namespace has no entry — VML, `urn:` Office legacy
 * namespaces, drawing extensions such as `a14:` — refuses the export.
 */

const DRAWINGML_MAIN_ELEMENTS = new Set([
  // graphic payloads and shape containers
  'graphic',
  'graphicData',
  'graphicFrame',
  'sp',
  'spPr',
  'grpSp',
  'grpSpPr',
  'cxnSp',
  'nvSpPr',
  'nvGrpSpPr',
  'nvCxnSpPr',
  'nvGraphicFramePr',
  'nvPr',
  'cNvPr',
  'cNvSpPr',
  'cNvGrpSpPr',
  'cNvCxnSpPr',
  'cNvGraphicFramePr',
  // images and fills
  'blip',
  'stretch',
  'fillRect',
  'srcRect',
  'tile',
  // geometry
  'xfrm',
  'off',
  'ext',
  'chOff',
  'chExt',
  'prstGeom',
  'avLst',
  'gd',
  'custGeom',
  'pathLst',
  'path',
  'moveTo',
  'lnTo',
  'arcTo',
  'quadBezTo',
  'cubicBezTo',
  'pt',
  'close',
  'fillToRect',
  // line and fill styles
  'ln',
  'headEnd',
  'tailEnd',
  'prstDash',
  'custDash',
  'ds',
  'round',
  'bevel',
  'miter',
  'solidFill',
  'noFill',
  'gradFill',
  'gsLst',
  'gs',
  'lin',
  'pattFill',
  'grpFill',
  // colours and colour transforms
  'schemeClr',
  'srgbClr',
  'sysClr',
  'prstClr',
  'scrgbClr',
  'hslClr',
  'tint',
  'shade',
  'comp',
  'inv',
  'gray',
  'gamma',
  'invGamma',
  'alpha',
  'alphaOff',
  'alphaMod',
  'alphaModFix',
  'alphaBi',
  'alphaRepl',
  'biLevel',
  'blur',
  'clrChange',
  'clrFrom',
  'clrTo',
  'clrRepl',
  'duotone',
  'grayscl',
  'hsl',
  'lum',
  'lumMod',
  'lumOff',
  'satMod',
  'satOff',
  'hueMod',
  'hueOff',
  'red',
  'green',
  'blue',
  'redOff',
  'redMod',
  'greenOff',
  'greenMod',
  'blueOff',
  'blueMod',
  'sepia',
  // effects
  'effectLst',
  'effectDag',
  'outerShdw',
  'innerShdw',
  'prstShdw',
  'glow',
  'softEdge',
  'reflection',
  'fillOverlay',
  'effect',
  'sp3d',
  'scene3d',
  'camera',
  'lightRig',
  'bevelT',
  'bevelB',
  'extrusionClr',
  'contourClr',
  'rot',
  'extLst',
  'ext',
  // links inside drawings
  'hlinkClick',
  'hlinkHover',
  // fonts
  'latin',
  'ea',
  'cs',
  'font',
  'sym',
  'script',
  // theme parts
  'theme',
  'themeElements',
  'clrScheme',
  'dk1',
  'lt1',
  'dk2',
  'lt2',
  'accent1',
  'accent2',
  'accent3',
  'accent4',
  'accent5',
  'accent6',
  'hlink',
  'folHlink',
  'fontScheme',
  'majorFont',
  'minorFont',
  'fmtScheme',
  'fillStyleLst',
  'lnStyleLst',
  'effectStyleLst',
  'bgFillStyleLst',
  'effectStyle',
  'effectRef',
  'fillRef',
  'lnRef',
  'fontRef',
  'bgRef',
  'style',
  'extraClrSchemeLst',
  'extraClrScheme',
  'objectDefaults',
  'spDef',
  'lnDef',
  'txDef',
  'graphicFrameLocks',
  'officeStyleSheet',
  'baseStyles',
  'clrMapOvr',
  // text bodies inside shapes
  'bodyPr',
  'lstStyle',
  't',
  'r',
  'rPr',
  'p',
  'pPr',
  'endParaRPr',
  'br',
  'fld',
  'defRPr',
  'lvl1pPr',
  'lvl2pPr',
  'lvl3pPr',
  'lvl4pPr',
  'lvl5pPr',
  'lvl6pPr',
  'lvl7pPr',
  'lvl8pPr',
  'lvl9pPr',
  'tabLst',
  'spcBef',
  'spcAft',
  'spcPts',
  'spcPct',
  'lnSpc',
  'buNone',
  'buChar',
  'buAutoNum',
  'buClr',
  'buSzPct',
  'buSzPts',
  'buFont',
  'buFontTx',
  'buClrTx',
  'buBlip',
  'buSzTx',
  // tables inside drawings
  'tbl',
  'tblPr',
  'tblGrid',
  'gridCol',
  'tc',
  'txBody',
  'tr',
  'tcPr',
  'bandRow',
  'bandCol',
  'firstRow',
  'firstCol',
  'lastRow',
  'lastCol',
])

const DRAWINGML_PICTURE_ELEMENTS = new Set([
  'pic',
  'nvPicPr',
  'cNvPr',
  'cNvPicPr',
  'blipFill',
  'spPr',
  'style',
])

const WP_DRAWING_ELEMENTS = new Set([
  'inline',
  'anchor',
  'extent',
  'effectExtent',
  'docPr',
  'cNvGraphicFramePr',
  'positionH',
  'positionV',
  'posOffset',
  'align',
  'wrapNone',
  'wrapSquare',
  'wrapTight',
  'wrapThrough',
  'wrapTopAndBottom',
  'wrapPolygon',
  'lineTo',
  'start',
  'simplePos',
])

const MATH_ELEMENTS = new Set([
  'mathPr',
  'mathFont',
  'brkBin',
  'brkBinSub',
  'smallFrac',
  'dispDef',
  'lMargin',
  'rMargin',
  'defJc',
  'wrapIndent',
  'wrapRight',
  'intLim',
  'naryLim',
  'interSp',
  'intraSp',
  'postSp',
  'preSp',
  'oMath',
  'oMathPara',
  'oMathParaPr',
  'f',
  'fName',
  'fPr',
  'num',
  'den',
  'sSup',
  'sSupPr',
  'sSub',
  'sSubPr',
  'sSubSup',
  'sSubSupPr',
  'sPre',
  'sPrePr',
  'sup',
  'sub',
  'deg',
  'degHide',
  'e',
  'nary',
  'naryPr',
  'limLow',
  'limLowPr',
  'limUpp',
  'limUppPr',
  'lim',
  'limLoc',
  'rad',
  'radPr',
  'd',
  'dPr',
  'begChr',
  'endChr',
  'sepChr',
  'chr',
  'pos',
  'vertJc',
  'ctrlPr',
  'r',
  'rPr',
  't',
  'm',
  'mPr',
  'mr',
  'mc',
  'mcPr',
  'mcs',
  'mcJc',
  'baseJc',
  'plcHide',
  'argPr',
  'argSz',
  'grow',
  'hideBot',
  'hideLeft',
  'hideRight',
  'hideTop',
  'strikeBLTR',
  'strikeH',
  'strikeTLBR',
  'strikeV',
  'sty',
  'subHide',
  'supHide',
  'transp',
  'zeroAsc',
  'zeroDesc',
  'zeroWid',
  'bar',
  'barPr',
  'borderBox',
  'borderBoxPr',
  'box',
  'boxPr',
  'eqArr',
  'eqArrPr',
  'func',
  'funcPr',
  'groupChr',
  'groupChrPr',
  'phantom',
  'phantomPr',
  'phantPr',
  'acc',
  'accPr',
  'aln',
  'alnScr',
  'brk',
  'lit',
  'nor',
  'scr',
  'count',
  'dist',
  'maxDist',
  'objDist',
  'rSp',
  'rSpRule',
  'type',
  'opEmu',
  'jc',
  'noBreak',
  'dMacro',
  'intChk',
  'funcApply',
  'msPre',
  'msSub',
  'msSubSup',
])

const WPS_ELEMENTS = new Set([
  'wsp',
  'cNvSpPr',
  'spPr',
  'style',
  'txbx',
  'bodyPr',
  'extLst',
])

const WPG_ELEMENTS = new Set(['wgp', 'cNvGrpSpPr', 'grpSp'])
const WPC_ELEMENTS = new Set(['wholeCanvas', 'bg', 'fg'])
const WP14_ELEMENTS = new Set(['sizeRelH', 'sizeRelW'])

/**
 * Element names allowed per embedded or extension namespace. A namespace
 * without an entry refuses every element it carries.
 */
export const EMBEDDED_ELEMENTS = new Map<string, ReadonlySet<string>>([
  [DRAWINGML_MAIN_NAMESPACE, DRAWINGML_MAIN_ELEMENTS],
  [DRAWINGML_PICTURE_NAMESPACE, DRAWINGML_PICTURE_ELEMENTS],
  [WP_DRAWING_NAMESPACE, WP_DRAWING_ELEMENTS],
  [MATH_NAMESPACE, MATH_ELEMENTS],
  [WPS_NAMESPACE, WPS_ELEMENTS],
  [WPG_NAMESPACE, WPG_ELEMENTS],
  [WPC_NAMESPACE, WPC_ELEMENTS],
  [WP14_NAMESPACE, WP14_ELEMENTS],
])
