/**
 * The OMML element vocabulary: every `m:` element name the schema
 * declares that the share-safe copy may emit, plus the phantom family
 * whose only purpose is invisible layout. The per-element `m:val` bounds
 * live in `share-safe-math-attributes.ts`; the hidden-content refusal the
 * element names feed sits in `share-safe-drawing-vocabulary.ts`.
 */

export const MATH_ELEMENTS = new Set([
  'mathPr',
  'mathFont',
  'brkBin',
  'brkBinSub',
  'smallFrac',
  'dispDef',
  'lMargin',
  'rMargin',
  'defJc',
  'wrapIndent',
  'wrapRight',
  'intLim',
  'naryLim',
  'interSp',
  'intraSp',
  'postSp',
  'preSp',
  'oMath',
  'oMathPara',
  'oMathParaPr',
  'f',
  'fName',
  'fPr',
  'num',
  'den',
  'sSup',
  'sSupPr',
  'sSub',
  'sSubPr',
  'sSubSup',
  'sSubSupPr',
  'sPre',
  'sPrePr',
  'sup',
  'sub',
  'deg',
  'degHide',
  'e',
  'nary',
  'naryPr',
  'limLow',
  'limLowPr',
  'limUpp',
  'limUppPr',
  'lim',
  'limLoc',
  'rad',
  'radPr',
  'd',
  'dPr',
  'begChr',
  'endChr',
  'sepChr',
  'chr',
  'pos',
  'vertJc',
  'ctrlPr',
  'r',
  'rPr',
  't',
  'm',
  'mPr',
  'mr',
  'mc',
  'mcPr',
  'mcs',
  'mcJc',
  'baseJc',
  'plcHide',
  'argPr',
  'argSz',
  'grow',
  'hideBot',
  'hideLeft',
  'hideRight',
  'hideTop',
  'strikeBLTR',
  'strikeH',
  'strikeTLBR',
  'strikeV',
  'sty',
  'subHide',
  'supHide',
  'transp',
  'zeroAsc',
  'zeroDesc',
  'zeroWid',
  'bar',
  'barPr',
  'borderBox',
  'borderBoxPr',
  'box',
  'boxPr',
  'eqArr',
  'eqArrPr',
  'func',
  'funcPr',
  'groupChr',
  'groupChrPr',
  'acc',
  'accPr',
  'aln',
  'alnScr',
  'brk',
  'lit',
  'nor',
  'scr',
  'count',
  'maxDist',
  'objDist',
  'rSp',
  'rSpRule',
  'type',
  'opEmu',
  'jc',
  'noBreak',
  'diff',
  'phant',
  'phantPr',
  'show',
  'shp',
  'cSp',
  'cGp',
  'cGpRule',
])

/**
 * OMML elements whose only purpose is to hide what they contain.
 * Phantoms render their operand invisibly while still occupying layout
 * space — a hidden carrier refuses rather than shipping under the copy.
 */
const MATH_HIDDEN_ELEMENTS = new Set([
  'phant',
  'phantPr',
  'phantPh',
  'phantom',
  'phantomPr',
  'show',
])

export function mathElementRefusesHidden(localName: string): boolean {
  return MATH_HIDDEN_ELEMENTS.has(localName)
}
