/**
 * Reference half of the element-scoped `w:` attribute vocabulary:
 * `w:val`-only carriers (style references, enums and counted values),
 * field machinery, note and bookmark identity, numbering and styles
 * identity, content controls, and the settings/web-settings vocabulary.
 * Formatting geometry lives in `share-safe-word-attribute-format.ts`;
 * `WML_ELEMENT_ATTRIBUTES` in `share-safe-word-attributes.ts` assembles
 * both tables.
 */

/** A `w:val`-only carrier. */
const VAL = ['val'] as const

export const WML_REFERENCE_ATTRIBUTES: ReadonlyArray<
  readonly [string, readonly string[]]
> = [
  // pure `w:val` carriers — style references, enums and counted values
  ...[
    'pStyle',
    'rStyle',
    'cnfStyle',
    'tblStyle',
    'name',
    'basedOn',
    'next',
    'link',
    'uiPriority',
    'divId',
    'jc',
    'outlineLvl',
    'textDirection',
    'textAlignment',
    'textboxTightWrap',
    'w',
    'kern',
    'position',
    'sz',
    'szCs',
    'highlight',
    'u',
    'effect',
    'vertAlign',
    'em',
    'fitText',
    'type',
    'trHeight',
    'gridSpan',
    'hMerge',
    'vMerge',
    'vAlign',
    'tblOverlap',
    'tblStyleRowBandSize',
    'tblStyleColBandSize',
    'lock',
    'label',
    'tabIndex',
    'appearance',
    'format',
    'maxLength',
    'listEntry',
    'entryMacro',
    'exitMacro',
    'size',
    'defaultTabStop',
    'characterSpacingControl',
    'decimalSymbol',
    'listSeparator',
    'consecutiveHyphenLimit',
    'hyphenationZone',
    'summaryLength',
    'clickAndTypeStyle',
    'defaultTableStyle',
    'stylePaneFormatFilter',
    'stylePaneSortMethod',
    'documentType',
    'view',
    'minVersion',
    'targetScreenSz',
    'pixelsPerInch',
    'panose1',
    'charset',
    'family',
    'pitch',
    'altName',
    'hps',
    'hpsRaise',
    'hpsBaseText',
    'lid',
    'rubyAlign',
    'ilvl',
    'numId',
    'abstractNumId',
    'numberingId',
    'start',
    'end',
    'startOverride',
    'lvlRestart',
    'lvlText',
    'lvlJc',
    'numFmt',
    'multiLevelType',
    'suff',
    'tmpl',
    'nsid',
    'lvlPicBulletId',
    'gridBefore',
    'gridAfter',
    'dateFormat',
    'storeMappedDataAs',
    'calendar',
    'fullDate',
  ].map((name): readonly [string, readonly string[]] => [name, VAL]),
  // field machinery
  ['fldChar', ['fldCharType', 'dirty', 'fldLock']],
  ['fldSimple', ['instr', 'dirty', 'fldLock']],
  // notes, bookmarks and links
  ['footnote', ['id', 'type']],
  ['endnote', ['id', 'type']],
  ['footnoteReference', ['id', 'customMarkFollows']],
  ['endnoteReference', ['id', 'customMarkFollows']],
  ['bookmarkStart', ['id', 'name', 'colFirst', 'colLast']],
  ['bookmarkEnd', ['id']],
  ['hyperlink', ['anchor', 'history', 'tgtFrame']],
  ['proofErr', ['type']],
  // numbering identity
  ['abstractNum', ['abstractNumId']],
  ['num', ['numId']],
  ['lvl', ['ilvl']],
  ['lvlOverride', ['ilvl']],
  ['numPicBullet', ['numPicBulletId', 'numberingId']],
  // styles
  ['style', ['type', 'styleId', 'default', 'customStyle']],
  [
    'latentStyles',
    [
      'count',
      'defLockedState',
      'defUIPriority',
      'defSemiHidden',
      'defUnhideWhenUsed',
      'defQFormat',
    ],
  ],
  [
    'lsdException',
    ['name', 'locked', 'uiPriority', 'semiHidden', 'unhideWhenUsed', 'qFormat'],
  ],
  // font-table record
  ['font', ['name']],
  // content controls and form fields
  ['text', ['multiLine']],
  ['listItem', ['val', 'displayText', 'value']],
  ['helpText', ['val', 'type']],
  ['statusText', ['val', 'type']],
  ['docVar', ['name', 'val']],
  // web settings
  ['div', ['id']],
  // settings
  ['zoom', ['val', 'percent']],
  ['proofState', ['spelling', 'grammar']],
  ['compatSetting', ['name', 'uri', 'val']],
  [
    'clrSchemeMapping',
    [
      'bg1',
      't1',
      'bg2',
      't2',
      'accent1',
      'accent2',
      'accent3',
      'accent4',
      'accent5',
      'accent6',
      'followedHyperlink',
      'hyperlink',
    ],
  ],
  [
    'activeWritingStyle',
    ['appName', 'dllVersion', 'nat', 'checkStyle', 'vendorID'],
  ],
]
