/*
 * Traefik configuration and the HTTP client the checks drive it with.
 *
 * The configuration builders emit exactly what Dokploy's Traefik reads: the
 * shipped `infra/traefik/entrypoints.yml` fragment is copied verbatim into the
 * generated main config, so the artifact under test is the file an operator
 * would apply. The client writes raw requests over `node:http` because the
 * checks need to pace a body, send one oversized header, or read a response
 * slowly — shapes `fetch` would normalise away.
 */
import { createHash } from 'node:crypto'
import { request as httpRequest } from 'node:http'
import { createServer } from 'node:net'

import { bearer } from '../api-runtime/http.mjs'
import { waitFor } from './docker.mjs'

export const API_HOST = 'api.obiter.test'
export const ORIGIN_HOST = 'origin.obiter.test'
export const DYNAMIC_DIR = '/etc/dokploy/traefik/dynamic'

// The paced upload is a quarter of the 25 MiB application cap per second, so it
// takes ~40s and is nowhere near the shipped 300s readTimeout while being far
// slower than the 5s control. The control uses a body that needs ~9.6s.
export const SLOW_UPLOAD_BYTES = 25 * 1024 * 1024
export const CONTROL_UPLOAD_BYTES = 6 * 1024 * 1024
export const LONG_STREAM_QUERY = 'chunks=20&chunkBytes=32768&intervalMs=500' // ~10s
export const STREAM_TOTAL_BYTES = 20 * 32768

const PACED_CHUNK_BYTES = 64 * 1024
const PACED_INTERVAL_MS = 100 // 64 KiB / 100ms = 640 KiB/s

export function sha256(buffer) {
  return createHash('sha256').update(buffer).digest('hex')
}

/** An OS-allocated loopback port, released for the container mapping. */
export function freePort() {
  return new Promise((resolvePort, reject) => {
    const probe = createServer()
    probe.on('error', reject)
    probe.listen(0, '127.0.0.1', () => {
      const address = probe.address()
      probe.close(() => resolvePort(address.port))
    })
  })
}

/** A synthetic text document of the requested size, for a streamable body. */
export function syntheticText(targetBytes) {
  const line =
    'Ingress boundary check: synthetic legal correspondence, no client data. ' +
    'Boundary fence title plan covenant easement conveyance counterpart.\n'
  const buffer = Buffer.from(line.repeat(Math.ceil(targetBytes / line.length)))
  return buffer.subarray(0, targetBytes)
}

const GENERATED_HEADER = `# Generated by scripts/api-ingress. The entryPoints block
# below is infra/traefik/entrypoints.yml, copied verbatim.`

/**
 * The local main config: Dokploy's file provider plus the shipped entrypoints.
 * The `certificatesResolvers` block mirrors Dokploy's default so the fragment's
 * `certResolver` reference resolves at load; no router under test uses TLS.
 */
export function staticConfig(entrypointsYaml, { debug }) {
  return `${GENERATED_HEADER}
providers:
  file:
    directory: ${DYNAMIC_DIR}
    watch: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: test@localhost
      storage: /tmp/acme.json
      httpChallenge:
        entryPoint: web
log:
  level: ${debug ? 'DEBUG' : 'INFO'}
accessLog: {}
${entrypointsYaml}`
}

export function dynamicConfig(backendService, { apiPort, originPort }) {
  return `http:
  routers:
    api:
      rule: "Host(\`${API_HOST}\`)"
      entryPoints: [web]
      service: api
    origin:
      rule: "Host(\`${ORIGIN_HOST}\`)"
      entryPoints: [web]
      service: origin
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://${backendService}:${apiPort}"
    origin:
      loadBalancer:
        servers:
          - url: "http://origin:${originPort}"
`
}

/** Raw request to the proxy with the routed Host header. */
export function apiRequest({
  port,
  path,
  method = 'GET',
  token,
  body,
  headers = {},
  timeoutMs = 30_000,
}) {
  return new Promise((resolveRequest) => {
    const request = httpRequest(
      {
        host: '127.0.0.1',
        port,
        path,
        method,
        headers: {
          Host: API_HOST,
          ...(token ? bearer(token) : {}),
          ...headers,
        },
      },
      (response) => {
        const chunks = []
        response.on('data', (chunk) => chunks.push(chunk))
        response.on('end', () =>
          resolveRequest({
            status: response.statusCode,
            headers: response.headers,
            body: Buffer.concat(chunks),
          }),
        )
      },
    )
    request.setTimeout(timeoutMs, () => request.destroy(new Error('timeout')))
    request.on('error', (error) =>
      resolveRequest({
        status: 0,
        headers: {},
        body: Buffer.alloc(0),
        error: error.message,
      }),
    )
    if (body) request.write(body)
    request.end()
  })
}

export async function healthThroughProxy(port) {
  const response = await apiRequest({ port, path: '/api/health' })
  let parsed = null
  try {
    parsed = JSON.parse(response.body.toString('utf8'))
  } catch {
    parsed = null
  }
  return { status: response.status, runtime: parsed?.runtime ?? null, parsed }
}

export function waitForRuntime(port, runtime, timeoutMs = 60_000) {
  return waitFor(
    async () => {
      const health = await healthThroughProxy(port)
      return health.status === 200 && health.runtime === runtime ? health : null
    },
    { timeoutMs, label: `api runtime=${runtime} through Traefik` },
  )
}

/** Read a response with pauses so socket backpressure has to drain. */
export function readSlowly({ port, path, token, pauseMs = 40 }) {
  return new Promise((resolveRead) => {
    const started = Date.now()
    let bytes = 0
    let chunks = 0
    let status = 0
    const hash = createHash('sha256')
    const request = httpRequest(
      {
        host: '127.0.0.1',
        port,
        path,
        headers: { Host: API_HOST, ...(token ? bearer(token) : {}) },
      },
      (response) => {
        status = response.statusCode
        response.on('data', (chunk) => {
          bytes += chunk.length
          chunks += 1
          hash.update(chunk)
          response.pause()
          setTimeout(() => response.resume(), pauseMs)
        })
        response.on('end', () =>
          resolveRead({
            status,
            bytes,
            chunks,
            sha256: hash.digest('hex'),
            elapsedMs: Date.now() - started,
            complete: true,
          }),
        )
        response.on('error', (error) =>
          resolveRead({
            status,
            bytes,
            chunks,
            sha256: hash.digest('hex'),
            elapsedMs: Date.now() - started,
            complete: false,
            error: error.message,
          }),
        )
      },
    )
    request.on('error', (error) =>
      resolveRead({
        status,
        bytes,
        chunks,
        sha256: hash.digest('hex'),
        elapsedMs: Date.now() - started,
        complete: false,
        error: error.message,
      }),
    )
    request.end()
  })
}

/**
 * Write a body at a fixed rate, honouring socket backpressure. `body` (when
 * given, as for a multipart upload) replaces the filler buffer, and
 * `onProgress` fires after each chunk so a caller can act — a shutdown check
 * signals SIGTERM while the body is still arriving.
 */
export function pacedUpload({
  port,
  host,
  path,
  totalBytes,
  body,
  headers = {},
  intervalMs = PACED_INTERVAL_MS,
  onProgress,
}) {
  return new Promise((resolveUpload) => {
    const started = Date.now()
    let sent = 0
    let status = 0
    let responseBody = ''
    const filler = Buffer.alloc(PACED_CHUNK_BYTES, 0x62)
    const request = httpRequest(
      {
        host: '127.0.0.1',
        port,
        path,
        method: 'POST',
        headers: {
          Host: host,
          'Content-Type': 'application/octet-stream',
          'Content-Length': String(totalBytes),
          ...headers,
        },
      },
      (response) => {
        status = response.statusCode
        response.on('data', (part) => {
          responseBody += part
        })
        response.on('end', () =>
          resolveUpload({
            status,
            responseBody,
            sent,
            elapsedMs: Date.now() - started,
            complete: true,
          }),
        )
      },
    )
    request.on('error', (error) =>
      resolveUpload({
        status,
        responseBody,
        sent,
        elapsedMs: Date.now() - started,
        complete: false,
        error: error.message,
      }),
    )
    const tick = () => {
      if (sent >= totalBytes) {
        request.end()
        return
      }
      const remaining = totalBytes - sent
      const size = Math.min(PACED_CHUNK_BYTES, remaining)
      const slice = body
        ? body.subarray(sent, sent + size)
        : filler.subarray(0, size)
      const writable = request.write(slice)
      sent += size
      onProgress?.({ sent, total: totalBytes, elapsedMs: Date.now() - started })
      if (writable) setTimeout(tick, intervalMs)
      else request.once('drain', () => setTimeout(tick, intervalMs))
    }
    tick()
  })
}

/** Read a stream to the end, measuring how much the proxy let through. */
export function readStream({ port, host, path }) {
  return new Promise((resolveRead) => {
    const started = Date.now()
    let bytes = 0
    let chunks = 0
    let status = 0
    const request = httpRequest(
      { host: '127.0.0.1', port, path, headers: { Host: host } },
      (response) => {
        status = response.statusCode
        response.on('data', (chunk) => {
          bytes += chunk.length
          chunks += 1
        })
        response.on('end', () =>
          resolveRead({
            status,
            bytes,
            chunks,
            elapsedMs: Date.now() - started,
            complete: true,
          }),
        )
        response.on('error', (error) =>
          resolveRead({
            status,
            bytes,
            chunks,
            elapsedMs: Date.now() - started,
            complete: false,
            error: error.message,
          }),
        )
      },
    )
    request.on('error', (error) =>
      resolveRead({
        status,
        bytes,
        chunks,
        elapsedMs: Date.now() - started,
        complete: false,
        error: error.message,
      }),
    )
    request.end()
  })
}

/** A request with one oversized (or normal) header, to the synthetic origin. */
export function headerProbe({ port, host, headerBytes, path = '/headers' }) {
  return new Promise((resolveProbe) => {
    const request = httpRequest(
      {
        host: '127.0.0.1',
        port,
        path,
        headers: { Host: host, 'X-Probe': 'a'.repeat(headerBytes) },
      },
      (response) => {
        const chunks = []
        response.on('data', (chunk) => chunks.push(chunk))
        response.on('end', () =>
          resolveProbe({
            status: response.statusCode,
            body: Buffer.concat(chunks).toString('utf8'),
          }),
        )
      },
    )
    request.setTimeout(20_000, () => request.destroy(new Error('timeout')))
    request.on('error', (error) =>
      resolveProbe({ status: 0, error: error.message }),
    )
    request.end()
  })
}
