import type { CorpusRelevanceBaseline } from './metrics'

// Observed floors from POST /api/search/fetch on the product corpus at
// documentCount 37938. Failures stay in the set; ranking work tightens
// these numbers rather than deleting the cases. heldPrecision moved with
// the case set (49 to 50 held): the added Donoghue query serves 1 held hit
// in 20, and every pre-existing case measured byte-identical before/after.
export const corpusRelevanceBaseline: CorpusRelevanceBaseline = {
  expectedCaseCount: 64,
  expectedDocumentCount: 37938,
  heldRecall: 1,
  heldPrecision: 0.5332,
  absentPrecision: 1,
  mrr: 0.9371,
  byQuery: {
    'party-okpabi': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-guest': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-guest-v-guest': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-vedanta': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-lungowe-v-vedanta': {
      recall: 1,
      ranks: [2],
      returnedHitCount: 20,
    },
    'party-miller': { recall: 1, ranks: [3], returnedHitCount: 20 },
    'party-gina-miller': { recall: 1, ranks: [2, 1], returnedHitCount: 8 },
    'party-prest': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-montgomery': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-lloyd-v-google': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-radmacher': { recall: 1, ranks: [1, 2, 3], returnedHitCount: 20 },
    'party-fearn': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-pimlico-plumbers': { recall: 1, ranks: [1], returnedHitCount: 9 },
    'party-patel-v-mirza': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-uber-bv': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-aslam-v-uber': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-harpur-trust': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-potanina': { recall: 1, ranks: [1], returnedHitCount: 13 },
    'party-fca-v-arch': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-arch-insurance': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-jones': { recall: 1, ranks: [4], returnedHitCount: 20 },
    'party-paul-v-wolverhampton': {
      recall: 1,
      ranks: [1],
      returnedHitCount: 14,
    },
    'party-zxc': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'party-swift-v-carpenter': { recall: 1, ranks: [3], returnedHitCount: 20 },
    'party-donoghue-stevnson': { recall: 1, ranks: [1], returnedHitCount: 20 },
    'cite-ewca-civ-2024-123': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2021-3': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2022-27': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2019-20': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2017-5': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2013-34': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2015-11': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2021-50': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2023-4': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2010-42': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2024-1': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2024-3': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2018-29': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2016-42': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2021-5': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2021-1': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2019-41': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-uksc-2022-21': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-ukpc-2021-3': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'cite-ewca-civ-2020-1295': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'id-uksc-2021-3': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'id-uksc-2022-27': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'id-uksc-2017-5': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'id-ewca-civ-2024-123': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'id-ukpc-2021-3': { recall: 1, ranks: [1], returnedHitCount: 1 },
    'absent-ewca-civ-2023-123': {
      recall: null,
      ranks: [],
      returnedHitCount: 20,
    },
    'absent-ewca-civ-2021-9999': {
      recall: null,
      ranks: [],
      returnedHitCount: 12,
    },
    'absent-ukhl-2003-1': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-uksc-2024-999': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-ukpc-2019-99': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-ewca-crim-2022-9999': {
      recall: null,
      ranks: [],
      returnedHitCount: 0,
    },
    'absent-uksc-2020-99': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-ewca-civ-2018-1': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-ewca-civ-1999-9999': {
      recall: null,
      ranks: [],
      returnedHitCount: 8,
    },
    'absent-ukpc-2015-1': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-uksc-2012-99': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-uksc-2023-99': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-ewca-civ-2026-1': { recall: null, ranks: [], returnedHitCount: 20 },
    'absent-ewhc-admin-2021-9999': {
      recall: null,
      ranks: [],
      returnedHitCount: 4,
    },
  },
}
